version: '3.8'

services:
  server:
    build:
      dockerfile: Dockerfile
      context: "./server"
      args:
        - REACT_APP_URL=survey # url ending on which the survey will be served. !!! Also needs to be changed in server/app/package.json ->homepage !!!
        - REACT_APP_PAGE_TITLE=SDSC-BW Potentialanalyse
    restart: always
    environment:
      - SERVER_PORT=3000
      - EMAIL_HOST=mail.host.com
      - EMAIL_PORT=587 #default 587
      - EMAIL_USERNAME=email
      - EMAIL_PASSWORD=password
      - SENDER_EMAIL="SDSC-BW" <info@sdsc-bw.de> #"Fred Foo" <foo@example.de>' format for friendly name
      - SDSC_RECEIVER_EMAIL=receiver@sdsc-bw.de
      - SEND_CLIENT_EMAIL=1 #If enabled sends Email to client (dataJSON must contain kontakt_email_adresse)
      #- GENERIC_REPORT=1  #Include if you want to use this app for a generic survey (will not include scores in the survey)
    ports:
      - "80:3000"